name: Trello ➡️ En proceso

on:
  push:
    branches:
      - 'feature/*'

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Extraer y validar shortLink de la rama
        id: extract
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          BRANCH_FULL=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_FULL#*/}
          SHORT=${BRANCH_NAME%%-*}
          echo "Extracted SHORT: '$SHORT'"

          if ! [[ $SHORT =~ ^[A-Za-z0-9]+$ ]]; then
            echo "❌ ERROR: '$SHORT' no es un shortLink válido." >&2
            exit 1
          fi

          echo "card_short=$SHORT" >> $GITHUB_OUTPUT

      - name: Mover tarjeta a “En proceso” en Trello
        run: |
          curl -s -X PUT \
            "https://api.trello.com/1/cards/${{ steps.extract.outputs.card_short }}/idList" \
            "?value=${{ secrets.TRELLO_LIST_IN_PROGRESS_ID }}" \
            "&key=${{ secrets.TRELLO_API_KEY }}" \
            "&token=${{ secrets.TRELLO_API_TOKEN }}" \
          -o /tmp/trello.txt -w "%{http_code}" \
          | { read code; echo "HTTP status: $code"; if [ "$code" != "200" ]; then
              echo "❌ Falló mover tarjeta. Response:"; cat /tmp/trello.txt; exit 1;
            fi; }
